version: '3.8'

services: 
  app:
    container_name: eventioner-app
    build:
      context: .
    env_file: .env
    command: npm run dev 
    volumes:
      - .:/usr/src/app/
      - /app/node_modules 
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - $API_PORT:$API_PORT
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
    stdin_open: true
    tty: true

  db:
    container_name: eventioner-db
    image: mariadb
    env_file: .env
    restart: always
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE 
      MYSQL_USER: $MYSQL_USER 
      MYSQL_PASSWORD: $MYSQL_PASSWORD 
    ports:
      - 3306:3306

volumes: 
  db-config:
  db-data:
